import type { Event } from "@/app/events/actions";
import { sponsors } from "./sponsors";

export const events: Event[] = [
  // ─── 2026 ────────────────────────────────────────────────────────────────────
  {
    id: "build-night-to-posthog-2026-07-08",
    title: "Build Night TO by TechTank x PostHog",
    pitch: "Hands-on build night — bring a project and ship alongside other builders",
    start_at: "2026-07-08T18:00:00",
    tags: ["Build Night"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/7mgyw1r2",
    cover_url: "/images/luma/72952b9f-3f56-4b9f-8384-8e5796e9da9a.jpeg",
    sponsors: [sponsors.posthog],
    youtubeUrl: "https://www.youtube.com/watch?v=_L96f12lZhM",
    albumUrl: "https://photos.app.goo.gl/Dw6Ke6Q7Ed1Dnkd27",
  },
  {
    id: "run-club-2026-06",
    title: "🚨 Mayday Mayday: We're Running Again 🏃‍♀️",
    pitch: "Community run club — all paces welcome",
    start_at: "2026-06-28T12:00:00",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/197e37yl",
    cover_url: "/images/luma/716c130b-902a-4bc9-b95e-f9e8354024db.jpeg",
    albumUrl: "https://photos.app.goo.gl/Yfk4caeg3Q9hjHk59",
  },
  {
    id: "everyones-a-builder-now-brainstation",
    title: "Everyone's a Builder Now: How AI is Reshaping Product, Security, Engineering, and the Modern Workflow",
    pitch: "How AI is reshaping product, security, and engineering workflows",
    start_at: "2026-06-01T18:00:00",
    capacity: 200,
    tags: ["Panel", "AI"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/sbd5tsj6",
    cover_url: "/images/luma/eeff8c97-bf57-449e-b516-6f06b19be8ad.jpeg",
    host: sponsors.brainstation,
    sponsors: [sponsors.docebo],
    speakers: [
      { name: "Kyle Lacy", title: "Chief Marketing Officer", company: "Docebo" },
      { name: "Scott Peacock", title: "SVP & Head of Product", company: "Docebo" },
      { name: "Nitin Chopra", title: "CIO & CISO", company: "Docebo" },
    ],
    youtubeUrl: "https://www.youtube.com/watch?v=0j0nLhOi6Ic",
    albumUrl: "https://photos.app.goo.gl/LtazsmigLB9WThoy8",
  },
  {
    id: "run-club-2026-05",
    title: "🌱 May I Have Your Attention Please: We're Running",
    pitch: "Community run club — all paces welcome",
    start_at: "2026-05-24T10:00:00",
    capacity: 55,
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/rop2u7iz",
    cover_url: "/images/luma/b5c82091-07a7-4ca9-81fc-ce5ae6d03db1.jpeg",
    albumUrl: "https://photos.app.goo.gl/G6hjagphvoWSSHfy5",
  },
  {
    id: "teaching-ai-design-system-7shifts",
    title: "Teaching AI to Use Your Design System",
    pitch: "Keeping AI-generated UI consistent with your design system",
    start_at: "2026-06-29T18:00:00",
    capacity: 80,
    tags: ["Tech Talk", "AI", "Design"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/r37zzrdi",
    cover_url: "/images/luma/998e4c11-5530-49d1-8225-e57ed2f23bbb.jpeg",
    host: sponsors["7shifts"],
    speakers: [
      {
        name: "Alex Andrade",
        title: "Senior Design Engineer",
        company: "7shifts",
        talkTitle: "Teaching AI to Use Your Design System",
      },
    ],
    youtubeUrl: "https://www.youtube.com/watch?v=Ta-DNbrSH38",
    albumUrl: "https://photos.app.goo.gl/KMTCBDtUQhV1DJk26",
  },
  {
    id: "supercollider-spring-fling-2026",
    title: "SUPERCOLLIDER Spring Fling — Toronto Tech Communities Networking Night",
    pitch: "Multi-community spring networking night at Left Field Brewery",
    start_at: "2026-04-27T18:00:00",
    venue: "Left Field Brewery (Liberty Village)",
    tags: ["Networking", "Social", "Multi-community"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/supercollider-spring-fling-2026",
    cover_url: "/images/luma/b3bae200-2226-4cd2-9796-5a7480abda7c.jpeg",
  },
  {
    id: "code-diversity-coffee-2026-05",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Welcoming coffee meetup for women and gender-diverse folks in tech",
    start_at: "2026-05-02T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/3ea6eq1s",
    cover_url: "/images/luma/bca86cee-3fdb-403a-bb09-ccc095690401.jpeg",
  },
  {
    id: "techtank-turns-3",
    title: "This ain't my first rodeo 🤠🪩 TECHTANK 3 YEAR ANNIVERSARY",
    pitch: "Celebrating three years of Toronto tech community",
    start_at: "2026-04-16T20:00:00",
    venue: "Dina's Tavern",
    tags: ["Anniversary", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/qwpt54ke",
    cover_url: "/images/luma/024f2a7f-8df2-47c2-b24d-a7c48aeab793.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipM-VmIz5kOG18HrCZIcQyfVLgKKsCQSS_SWIo2ODM5DME1Z7BEoQOoMD5JbBujfkA?key=WVVLWkFVXzNsYkpTNkN4MU5uYUNRNEpDQVZuVzJ3",
  },
  {
    id: "ci-optimization-brainstation",
    title: "CI Optimization: Built-In Flags You're Probably Not Using",
    pitch: "Save CI time with native caching flags your pipeline is missing",
    start_at: "2026-04-13T18:30:00",
    capacity: 100,
    tags: ["Tech Talk", "DevOps", "CI/CD"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/7h4g008b",
    cover_url: "/images/luma/5d9909f0-ece1-4b30-bdde-b4af7ec8b4da.jpeg",
    sponsors: [sponsors.brainstation],
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipN3f4J0Ya2sv76VCQXhdkKipehavLCc3v4kcdfwqqosjY2jN-KWfT3X4wrqCiRy4w?key=WEF6OUk3alhLb3dzOEJ5SWlsU2tVM2x1eDkxNUpn",
    speakers: [
      {
        name: "Emily Xiong",
        title: "Software Developer",
        company: "Stackadapt",
        talkTitle: "Save CI Time with Built-In Flags",
      },
    ],
  },
  {
    id: "code-diversity-coffee-2026-04",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2026-04-11T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/cye39lls",
    cover_url: "/images/luma/bca86cee-3fdb-403a-bb09-ccc095690401.jpeg",
  },
  {
    id: "code-diversity-iwd-pottery-2026",
    title: "Code Diversity × TigerBaby: IWD Pottery Workshop — Clay & Connection",
    pitch: "International Women's Day pottery workshop for women in tech",
    start_at: "2026-03-14T11:00:00",
    venue: "Creeds Coffee Bar",
    tags: ["Social", "CodeDiversity", "Workshop"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/wzaj4vzy",
    cover_url: "/images/luma/2bbde763-1e1f-429d-8491-c9af40b479ab.jpeg",
  },
  {
    id: "code-diversity-coffee-2026-01",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2026-01-17T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/mbafwfgu",
    cover_url: "/images/luma/799c848f-b71f-4d62-99a1-a93afcf4089c.jpeg",
  },
  // ─── 2025 ────────────────────────────────────────────────────────────────────
  {
    id: "code-diversity-coffee-2025-12",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-12-20T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/q3w5yoeb",
    cover_url: "/images/luma/b7019fa7-2bd2-4607-b69a-f2ad33cbc09c.jpeg",
  },
  {
    id: "santacollider-2025",
    title: "Santacollider: Toronto Tech Community Holiday Party",
    pitch: "Annual multi-community holiday party at The Pilot",
    start_at: "2025-12-09T18:00:00",
    venue: "The Pilot",
    tags: ["Social", "Holiday", "Multi-community"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/312122530/",
    cover_url: "/images/meetup/highres_531423712.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-11",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-11-15T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/bafv7trd",
    cover_url: "/images/luma/b7019fa7-2bd2-4607-b69a-f2ad33cbc09c.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-10",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-10-18T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/308164572/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "battle-frameworks-underdog",
    title: "🥊 Battle of the Frameworks: Underdog edition 🥊",
    pitch: "Framework showdown with a twist — the underdogs get their moment",
    start_at: "2025-10-08T18:00:00",
    venue: "Rakuten Kobo",
    tags: ["Tech Talk", "Panel", "Frameworks"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/u2mzq5bn",
    cover_url: "/images/luma/71320253-f6a1-441e-95d5-4217915cd1db.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipPPmVC7Jg5of2zIp8CgLxyavCSvyu-3ekKf_nEVwqqNA3lX4VBuVijVBSvZ62dNng?key=ZmtQTTRtUWYzejJwaXV5Wi1rOHl1TmxhTVNJYmRR",
  },
  {
    id: "agentic-programming-7shifts",
    title: "Agentic Programming 101 🚀",
    pitch: "Introduction to AI agents and autonomous programming",
    start_at: "2025-09-29T18:00:00",
    tags: ["Tech Talk", "AI", "Beginner-friendly"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/s6f56qtz",
    cover_url: "/images/luma/f75dc08b-1fe1-4bb4-acd0-7dce871d028e.jpeg",
    host: sponsors["7shifts"],
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNHIuIQ3GEwyuE7hRn3rrREKk2jRULCv3DkSatNFoAVgNYpQrzOd3VHmpsbT5L15w?key=UVFQal9MbTNiVmZhUnlOQVZ0U05iR3BfRlJxdFh3",
  },
  {
    id: "mentorship-meetup-2025",
    title: "Mentorship Meetup: For Tech Talent in Their First 1–5 Years",
    pitch: "Coffee chat and peer mentorship for early-career developers",
    start_at: "2025-09-13T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Mentorship", "Career", "Beginner-friendly"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/c8bxwh5z",
    cover_url: "/images/luma/c91fbca8-6e5f-4700-babe-9efbb757777e.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-09",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-09-06T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/308163824/",
    cover_url: "/images/meetup/highres_528812977.jpeg",
  },
  {
    id: "buns-funds-bbq-2025",
    title: "🍔Buns & Fun(d)s🍔: Flippin' those Burgers with TechTank!",
    pitch: "Summer burger cookout with the TechTank community",
    start_at: "2025-08-02T13:00:00",
    tags: ["Social", "Food", "Summer"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/u6agrnb8",
    cover_url: "/images/luma/c52a0c30-c4fa-4fd5-b46c-00c6f31728e5.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-08",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-08-02T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/308163788/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "softball-sashimis-2025",
    title: "Softball Sashimis",
    pitch: "TechTank's summer softball game",
    start_at: "2025-06-21T12:00:00",
    tags: ["Sports", "Social"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMpnt5xDbFhqPFjq-d3e6NNoGiRUMTXxxbCQ-jTbOPnEE1tx6RMZEDt6s0ILEOetA?key=M1BBanJKUDdQWWdJMW41aFJoMUExakRwTzhrQWlB",
  },
  {
    id: "supercollider-techweek-2025",
    title: "SUPERCOLLIDER: Toronto Tech Week After Party",
    pitch: "Multi-community after party wrapping up Toronto Tech Week 2025",
    start_at: "2025-06-27T20:00:00",
    venue: "Greta Bar",
    tags: ["Social", "Tech Week", "Multi-community"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/307828751/",
    cover_url: "/images/meetup/highres_527960195.jpeg",
  },
  {
    id: "techweek-codediversity",
    title: "✨CodeDiversity✨ by TechTank & 7shifts",
    pitch: "Special CodeDiversity event during Toronto Tech Week at 7shifts HQ",
    start_at: "2025-06-25T18:00:00",
    tags: ["Tech Talk", "CodeDiversity", "Tech Week"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/mbmwbu15",
    cover_url: "/images/luma/c9166e5b-8fd8-453a-abb8-a9d8cbe1cc0d.jpeg",
    host: sponsors["7shifts"],
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMingUvuBFdNA4ES6wYi3UCHzRT3k9Il3wlWnFoUu_-5X8jztaoTjtAloU7TLIMJg?key=LXo2S0U1LXE2RmpJMk1HQXhfb0NISG1ncE1md1VR",
  },
  {
    id: "code-diversity-coffee-2025-05",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-05-24T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/307465132/",
    cover_url: "/images/meetup/highres_527561328.jpeg",
  },
  {
    id: "anniversary-spinco",
    title: "404: Fatigue Not Found [Our 2nd Anniversary CycleParty 🥳]",
    pitch: "Celebrating two years with spin and socializing",
    start_at: "2025-04-12T14:30:00",
    venue: "SPINCO Toronto Downtown",
    tags: ["Anniversary", "Sports", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/ekdq0p25",
    cover_url: "/images/luma/f6eb44a9-e019-40cf-b3b7-87eeea4cc5a5.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNsmSeqY9wxLMtqnFkDoPaj4X5T-cmuUkYkVHYHPUopyT4-b_IYhiPajDguMT-CSQ?key=NGlBeXM1bERMeDVKeGNXR2NZOWN5WG9PakZackRR",
  },
  {
    id: "code-diversity-coffee-2025-04",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-04-26T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/306889689/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "saas-cloud-migration",
    title: "Lightning Talks: Migrating a SaaS Product across Cloud Providers",
    pitch: "Lightning talks from senior engineers on cloud migration",
    start_at: "2025-04-10T18:00:00",
    venue: "Vena Solutions",
    tags: ["Tech Talk", "Cloud", "Architecture"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/306752010/",
    cover_url: "/images/meetup/highres_526850936.jpeg",
    sponsors: [sponsors.vena],
    speakers: [
      { name: "Saiid Douaihy", title: "Senior Software Manager", talkTitle: "Cloud Migration Strategies" },
      { name: "Pawan Keer", title: "Senior Software Development Manager", talkTitle: "Infrastructure at Scale" },
      { name: "Lucas Tran", title: "Senior Software Developer", talkTitle: "Lessons from the Trenches" },
    ],
    youtubeUrl: "https://www.youtube.com/watch?v=4MSJq2GBsIc",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipOb1lKTP_ktVaptdlB6GndudP3YQ77pW6BR3IxcDA2YV86ZNaHZe3M0Hp2iD6UoLA?key=SGxsS0xFRVRNZGdFVGJVQ1ZXN1ZtODBrZDNrNzRR",
  },
  {
    id: "code-diversity-coffee-2025-03",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-03-15T11:00:00",
    venue: "Prema Coffee and Bar",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/306586846/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "code-diversity-coffee-2025-02",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-02-15T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/305857202/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "cross-browser-extensions-cohere",
    title: "Building Cross-Browser Extensions: Challenges and Best Practices",
    pitch: "Building extensions that work everywhere",
    start_at: "2025-01-28T18:00:00",
    tags: ["Tech Talk", "Browser Extensions"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/305400630/",
    cover_url: "/images/meetup/highres_525722753.jpeg",
    host: sponsors.cohere,
    youtubeUrl: "https://www.youtube.com/watch?v=f8ONw6O_rco",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMrTfiNbI7_NSGioh-DLR6Slvp51pBjf1cShVzeToyKNr982BbkOEPmrqFYhd7vMg?key=VUp4V1ZGNzFibHBpRUNESkZYQ3BhVElob1RsdmdB",
  },
  {
    id: "code-diversity-coffee-2025-01",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2025-01-11T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/305395398/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  // ─── 2024 ────────────────────────────────────────────────────────────────────
  {
    id: "bits-bytes-bowties",
    title: "TechTank Toronto Holiday Party: Bits, Bytes & Bowties!",
    pitch: "Holiday party celebrating two years of TechTank",
    start_at: "2024-12-20T19:00:00",
    venue: "111 St Clair Ave W",
    tags: ["Anniversary", "Social", "Holiday"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/eqp4ccn5",
    cover_url: "/images/luma/2671403b-57d3-4af9-b22d-2b3879c7b4dc.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNaxy4wPaRA3EwJOduVBxlFXvGGqBsDmYRoAFw7_ChOrWGOjRo8Kk1TKYA5tiaE6g?key=ZHVrQjhicDk2c0w3dG9tQVc1MlRGMmV4cTRUc1d3",
  },
  {
    id: "code-diversity-coffee-2024-12",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2024-12-14T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/304806485/",
    cover_url: "/images/meetup/highres_524928803.jpeg",
  },
  {
    id: "wreck-the-rack",
    title: "Wreck the Rack: Techtank's Pool Hall Battle 🎱👊",
    pitch: "Competitive pool night for the tech community",
    start_at: "2024-11-23T17:00:00",
    venue: "Rivoli Toronto",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/8qe5mdb7",
    cover_url: "/images/luma/7445101b-ae32-40a1-b19a-c8f36ad2529a.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipOXFVlljbwPWfZ2MVv5rhWpTIaWzLb6Jdfp9aqRvtYP241OIvn3cbVMN-qooI1Fmg?key=ZkY0eVZvQXNpQXRZYUVCRTk1ZFEybnpZejJSRFlR",
  },
  {
    id: "code-diversity-coffee-2024-11",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2024-11-16T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/304348630/",
    cover_url: "/images/meetup/highres_524471440.jpeg",
  },
  {
    id: "gen-ai-rag-fpa",
    title: "Fueling Growth: Generative AI & RAG Applications in FP&A",
    pitch: "How AI is transforming financial planning and analysis",
    start_at: "2024-11-14T18:00:00",
    venue: "Vena Solutions",
    tags: ["Tech Talk", "AI", "FinTech"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/304263016/",
    cover_url: "/images/meetup/highres_524451822.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=2UTsy-Lbulk",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMfuV2mdrwgETwmivv4zQUu8pSRAzOG0D9J6j4nCpnNDKPMAgWL5ru6sYqMaMOOQg?key=OGJrMmFMR2NGT1IzaGxqTVFIRjVlaVJJbXNSaGd3",
  },
  {
    id: "edtech-ai-accessibility",
    title: "EdTech at the Crossroads: AI, Accessibility, and the Evolving Classroom",
    pitch: "Panel discussion on the future of education technology",
    start_at: "2024-10-28T18:00:00",
    venue: "Rakuten Kobo",
    tags: ["Panel", "EdTech", "AI", "Accessibility"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/303655206/",
    cover_url: "/images/meetup/highres_523810554.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=N50r7eIEIS0",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMwzeGDJqNkRSSagw_D8v3F73XeaPR9kmpQcpYjHCCuMx7nZ94feDaTGMA55whrLg?key=QzdzTnpRdHpiaHNaOE0zNnVIUE5EQlMxM0kxYzFR",
  },
  {
    id: "cypress-overwhelmed-dev",
    title: "Cypress for the Overwhelmed Developer",
    pitch: "Practical Cypress testing for developers who feel behind on testing",
    start_at: "2024-10-01T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Testing", "Web Dev"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/303601353/",
    cover_url: "/images/meetup/highres_523676979.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=cZHiIMuynYE",
  },
  {
    id: "forensics-rsc",
    title: "The Forensics of React Server Components",
    pitch: "Deep dive into how RSC actually works",
    start_at: "2024-09-18T18:00:00",
    venue: "Points.com",
    tags: ["Tech Talk", "React", "Web Dev"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/302940980/",
    cover_url: "/images/meetup/highres_523034935.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=NOlSKs5PLpM",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMPoK9UuL4g8MKPP8Tk8tI2FTppYtQQ-Nf0ga6DZXjFmqXT5SHTYikca8rhmltqhg?key=djduZGhZaHpJTi04SEZ2SVg3NUo0ZTRqcUlVY0Rn",
  },
  {
    id: "code-diversity-coffee-2024-09",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2024-09-14T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/303330348/",
    cover_url: "/images/meetup/highres_521950379.jpeg",
  },
  {
    id: "waterworks-2024",
    title: "Waterworks with da Tank 💦",
    pitch: "Social evening at the Waterworks Food Hall",
    start_at: "2024-10-26T18:00:00",
    venue: "Waterworks Food Hall",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/fmi3zf6a",
    cover_url: "/images/luma/5d8689b6-286d-4498-92e6-a6eaa8ec97fa.jpeg",
  },
  {
    id: "fyre-festival",
    title: "FYRE FEST",
    pitch: "TechTank's infamous summer social",
    start_at: "2024-09-28T16:00:00",
    venue: "Olympic Island",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/jkr3i7pz",
    cover_url: "/images/luma/f26d4d6d-417f-4d0e-a901-c0094391be56.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMgtyV8CNEuz-qajiP1CHJXhOThudbAQwu8JRpN_OSpPnjsb1H8PBPNI1old3yukQ?key=TVZaMExWQnVWQ1RvRlFFVGdQVGZCV3BXQ3k0ZlF3",
  },
  {
    id: "ai-insights-experts",
    title: "Unlocking AI: In-Depth Insights from Leading Experts",
    pitch: "Panel with AI industry leaders",
    start_at: "2024-08-15T18:00:00",
    venue: "1 Roof Garden Lane",
    tags: ["Panel", "AI"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/302337555/",
    cover_url: "/images/meetup/highres_522500582.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=RUco7XrbMqk",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMlGtrOSia0VXZaDqAcjItENfxwXFdxJO2A9QCKGwXcRPn46nY5e_DB9puMgfky9Q?key=eWNXOGh0SEZqcDdRaDVwRHVEWEF5SjBfRkRvTzFn",
  },
  {
    id: "code-diversity-coffee-2024-08",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2024-08-10T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/302503778/",
    cover_url: "/images/meetup/highres_521950379.jpeg",
  },
  {
    id: "tank-sports-2024",
    title: "✨🥎 TANKSPORTS 🏐✨",
    pitch: "Multi-sport summer event",
    start_at: "2024-08-31T15:00:00",
    tags: ["Sports", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/cidoy6p6",
    cover_url: "/images/luma/1dc01730-5cbd-466a-8f80-ef9e420a29bb.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNm1fut4HKxSRTpQ-6RkNQDkXsrzHhYfCaQwkoZAOWpw6b64L3iLU1yA3MHl_r8aQ?key=M2pWYXcySC1pazV4dzdxX2hIMFc5RnN6SHA3Q1d3",
  },
  {
    id: "tankolympics",
    title: "🏅TANKOLYMPICS | Return to Ocean Mandate 🌊",
    pitch: "Olympic-themed games and competitions",
    start_at: "2024-07-27T15:00:00",
    tags: ["Sports", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/55hizq8f",
    cover_url: "/images/luma/b6c5f6a3-1f3a-4ebd-9d29-075b9d6d74dc.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMaV0hBrR-eYX20MmtDBemZSZGUE3Y_kvO0JF9Cfm4crS27KpoU9tuY2u1aGNXWAA?key=OHk5TlJRNklhVTFXMzNGYTZ5Y09qOTN5ejM0RWtn",
  },
  {
    id: "mini-webpack-scratch",
    title: "Building a Mini Webpack from Scratch",
    pitch: "Understand how bundlers work by building one yourself",
    start_at: "2024-07-16T18:00:00",
    venue: "225 King St W",
    tags: ["Tech Talk", "Web Dev", "JavaScript"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/301699806/",
    cover_url: "/images/meetup/highres_521809945.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=iIjdAXX-oD4",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNyu6nkeQkkImW1usVfuDT6nr64NVj_WG5P6geHbZlDnLnKbZFP0kMGkovhsji1oA?key=R292TkpacE9ybHVMNTlfdVhvRHYtVGJEbFlZa0xn",
  },
  {
    id: "softball-sashimis-2024",
    title: "Softball Sashimi's",
    pitch: "Summer softball game",
    start_at: "2024-07-13T12:00:00",
    tags: ["Sports", "Social"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMmBy4aNt0rNAsHwMagst6jvo93awXW5yyWd4yCw9g5u0vdHpN7BRRHedJ8ofNEpQ?key=TXRZZ2FCazlCSFROZmdmQ1cwYXMwbmxYXy1ldmln",
  },
  {
    id: "code-diversity-coffee-2024-07",
    title: "Code Diversity Monthly Coffee Chats",
    pitch: "Monthly coffee chat for women and gender-diverse folks in tech",
    start_at: "2024-07-13T11:00:00",
    venue: "Carbonic Coffee",
    tags: ["Coffee Chat", "CodeDiversity", "Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/301852269/",
    cover_url: "/images/meetup/highres_521950379.jpeg",
  },
  {
    id: "sausages-cause-bbq",
    title: "Sausages for a Cause BBQ",
    pitch: "Charity BBQ event",
    start_at: "2024-06-15T12:00:00",
    tags: ["Social", "Charity"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNM9FBTNWpRR8DWT99MItot1HtgKiLEccHtwjYZIXBqPyQa8s4-ATrTlPNbCjf1gA?key=WGhjeENGV3VlZ1NpV3lQWjV6bE9OXzJ6b2lEaWN3",
  },
  {
    id: "networking-101-2024",
    title: "Networking 101",
    pitch: "How to network effectively in the tech industry",
    start_at: "2024-06-04T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Networking"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/301198832/",
    cover_url: "/images/meetup/highres_521252023.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=Fz-AfRrlzLM",
  },
  {
    id: "engineering-wellness-2024",
    title: "Engineering Wellness: Innovations and Challenges in Health Tech",
    pitch: "Exploring how technology is transforming healthcare delivery",
    start_at: "2024-05-16T18:00:00",
    venue: "1 Roof Garden Lane",
    tags: ["Tech Talk", "HealthTech", "Panel"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/300591167/",
    cover_url: "/images/meetup/highres_520941912.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=tMoqGyfVkGA",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMllK8NZdIjH0tP8lf0fw7JoQzXgse-6qCsWP2Kvh1lKWdGAiz_a1eeocYuoAntrA?key=cUphRG83Mzg1X0pSVzY2OTJfNTZ5Wlota20tY0pn",
  },
  {
    id: "ai-prompting-101",
    title: "AI Prompting 101",
    pitch: "Fundamentals of prompt engineering for developers",
    start_at: "2024-05-14T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "AI", "Beginner-friendly"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/300782288/",
    cover_url: "/images/meetup/highres_520806256.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=m7wvLa3sUe4",
  },
  {
    id: "anniversary-social-2024",
    title: "Anniversary Social",
    pitch: "Celebrating one year of TechTank",
    start_at: "2024-04-20T12:00:00",
    tags: ["Anniversary", "Social"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipN5YllsNHTVeUJKlSnd8bD4jyTo6muTTiMdHifF3DhT0olsYLxMbHynTtJ8jHJ7Uw?key=a1NmcTQ1VUpwWVB1OXNpb0tzeVRhN2hmM1NqcEFR",
  },
  {
    id: "epic-quest-javascript",
    title: "The Epic Quest of Javascript through Time and Cyberspace",
    pitch: "A sweeping history of JavaScript's evolution and where it's headed",
    start_at: "2024-04-24T18:00:00",
    venue: "482 Front St W",
    tags: ["Tech Talk", "JavaScript", "Web Dev"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/300175753/",
    cover_url: "/images/meetup/highres_520152027.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=Q5DvWKxpaBE",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNLPqEiBg7_95ZuKAxeC9GxdOVSUf3RmG8a5Hr5LWmBP8jRnPDGXNlBqkA4Sf2aXQ?key=UUltWXp4ODRJcDFYaXhOLXVrUE1GcGozZ0c0SFFR",
  },
  {
    id: "track-field-2024",
    title: "Track & Field with da Tank!",
    pitch: "Community social at Track & Field on College — drinks, bocce, and shuffleboard",
    start_at: "2024-03-30T18:00:00",
    venue: "Track & Field",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/mhy53r9s",
    cover_url: "/images/luma/default-standard2.jpeg",
  },
  {
    id: "pathfinders-2024",
    title: "Pathfinders: Celebrating Diversity and Innovation in Tech",
    pitch: "Panel celebrating diverse paths and perspectives in the tech industry",
    start_at: "2024-03-26T18:00:00",
    tags: ["Panel", "CodeDiversity", "Career"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/299326496/",
    cover_url: "/images/meetup/highres_519276676.jpeg",
    host: sponsors.cohere,
    youtubeUrl: "https://www.youtube.com/watch?v=nRoKA93lJqY",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipOn_EKK627wNTlgtoEjoRR-RIYqwDMZfV8cdxNx5-MAXTT_pvwWZAU3Jd8fgsZ2Lg?key=eG9aR1A1NzhQa01MN09TSGFGUkxnaldjcTJ2WHhR",
  },
  {
    id: "accessible-nav-menus",
    title: "It's more than a <nav>: Making accessible navigation menus",
    pitch: "Practical guide to building accessible navigation for the web",
    start_at: "2024-03-05T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Accessibility", "Web Dev"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/299380715/",
    cover_url: "/images/meetup/highres_519308057.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=Zuvta9giDOM",
  },
  {
    id: "generative-ai-developers-2024",
    title: "Generative AI for Developers",
    pitch: "Hands-on introduction to building with generative AI tools",
    start_at: "2024-02-22T18:00:00",
    venue: "Microsoft Reactor Toronto",
    tags: ["Tech Talk", "AI", "Workshop"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/298712672/",
    cover_url: "/images/meetup/highres_518649638.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=wv3tPtDrl_E",
  },
  {
    id: "coding-with-character",
    title: "Coding with Character",
    pitch: "How character and ethics shape better software engineers",
    start_at: "2024-02-21T20:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Culture"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/299017176/",
    cover_url: "/images/meetup/highres_518943016.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=Z1Ka1jsRW7E",
  },
  {
    id: "containerization-101",
    title: "Containerization 101: Docker and Beyond",
    pitch: "Demystifying Docker and container orchestration for developers",
    start_at: "2024-02-13T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "DevOps", "Docker"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/298854685/",
    cover_url: "/images/meetup/highres_518949413.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=lYQMYnnb6Kw",
  },
  {
    id: "cest-what-2024",
    title: "C'est What with da Tank!",
    pitch: "Pub social at C'est What with the TechTank community",
    start_at: "2024-02-24T17:00:00",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/techtank-feb2024-social",
    cover_url: "/images/luma/default-retro1.jpeg",
  },
  {
    id: "css-chronicles-2024",
    title: "CSS Chronicles: Navigating the Newest CSS Features",
    pitch: "A tour of the latest CSS features shipping in modern browsers",
    start_at: "2024-02-01T18:00:00",
    venue: "Intuit Canada",
    tags: ["Tech Talk", "CSS", "Web Dev"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/298329281/",
    cover_url: "/images/meetup/highres_518418480.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=JW0Nc5W7yEY",
  },
  {
    id: "cottage-trip",
    title: "Cottage Trip",
    pitch: "Winter getaway for the community",
    start_at: "2024-02-17T12:00:00",
    tags: ["Social", "Trip"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipOdL17zISJwXuA-sOQpNz71wSZ5plWDiQ112VjuKLxMFMX3hLObJUJ6v5J_c-asHA?key=U3BrY3NOVnk3eHBLRUJYMHFDNnBVMmJ0eFpTbm9B",
  },
  {
    id: "burnout-in-tech",
    title: "Rekindling the Flame: Navigating and Overcoming Burnout in Tech",
    pitch: "Honest conversation about burnout, recovery, and sustainable engineering",
    start_at: "2024-01-30T20:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Wellness"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/298283794/",
    cover_url: "/images/meetup/highres_518284688.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=q_aFpilEqMk",
  },
  {
    id: "feature-flagging-primer",
    title: "There's a Flag for That! A Developer's Primer on Feature Flagging",
    pitch: "How feature flags enable safer deployments and experimentation",
    start_at: "2024-01-09T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "DevOps", "Engineering"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/298165707/",
    cover_url: "/images/meetup/highres_518139051.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=KbUbw5QNPfo",
  },
  // ─── 2023 ────────────────────────────────────────────────────────────────────
  {
    id: "holiday-jam-2023",
    title: "Holiday Jam 2023",
    pitch: "TechTank's annual holiday social",
    start_at: "2023-12-14T12:00:00",
    tags: ["Social", "Holiday"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNJCcEC8dFz06_EsD32Tpot7evg7OY9ke9lb3Qs8itCUKgczd9V3iTdaKXVPb5qTw?key=S1RNYjVFRjZyRXRVQzFBR3lGVk1KRFJPOUlIQjJn",
  },
  {
    id: "skating-2023",
    title: "Skating with the Tank",
    pitch: "Ice skating social at Nathan Phillips Square",
    start_at: "2023-11-25T17:00:00",
    venue: "Nathan Phillips Square",
    tags: ["Social", "Sports"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/rqp4c62p",
    cover_url: "/images/luma/default-standard4.jpeg",
  },
  {
    id: "figma-devmode-workshop",
    title: "Figma Workshop: Devmode Tips and Tricks",
    pitch: "Level up your Figma workflow with Dev Mode features",
    start_at: "2023-12-05T19:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Design", "Workshop"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/297602552/",
    cover_url: "/images/meetup/highres_517574457.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=r0jrByKPu8E",
  },
  {
    id: "app-performance-deep-dive",
    title: "You've deployed... But how is your app performing?",
    pitch: "Monitoring, observability, and performance tuning for production apps",
    start_at: "2023-11-30T18:00:00",
    venue: "Rakuten Kobo",
    tags: ["Tech Talk", "DevOps", "Performance"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/297145894/",
    cover_url: "/images/meetup/highres_517035730.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=Q89KAMThfCw",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipN7795hAt6xtwWmIIPlBoijkf8svVZFKd4v7vTrDfhJdYe0u5DAn8wSlT4bNKgHig?key=Q1o4MzdZT1dWSHlzS0QyS0E0Qk1jSzVUSTNvTnZB",
  },
  {
    id: "transitioning-fullstack",
    title: "Transitioning to Full Stack and Beyond: Broadening Your Tech Horizons",
    pitch: "Strategies for developers looking to expand across the full stack",
    start_at: "2023-11-22T20:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Full Stack"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/297176805/",
    cover_url: "/images/meetup/highres_517192330.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=xbp1Psv2DiY",
  },
  {
    id: "cracking-a11y-code",
    title: "Cracking the A11y Code: Web Accessibility Basics for Beginners",
    pitch: "Practical introduction to making your web apps more accessible",
    start_at: "2023-11-07T20:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Accessibility", "Beginner-friendly"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/296957170/",
    cover_url: "/images/meetup/highres_516817887.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=-X1L81xpBtc",
  },
  {
    id: "niagara-glen-hike",
    title: "Niagara Glen Hike",
    pitch: "Fall hike at Niagara Glen",
    start_at: "2023-10-28T12:00:00",
    tags: ["Social", "Outdoors"],
    status: "past",
    guest_count: 0,
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipOg2itOXIvPeeQKFEFScI2UCeOojdcuGpMGoJXJftFFaKlCVDhzhdkk2PNfrICpzA?key=TmRwakJkdl8zMWlYZDM2dlZiT2ZUSWwwN1U2MmtR",
  },
  {
    id: "halloween-2023",
    title: "🎃 Halloween Party 🎃 with Techtank",
    pitch: "Spooky season social",
    start_at: "2023-10-28T17:30:00",
    tags: ["Social", "Holiday"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/tou5yec8",
    cover_url: "/images/luma/4be95679-e8c7-4149-bbba-60b80ff57c04.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipMbVRHwXl8qR8eWRaxk0jqxbUxRBD4ic1arOmYFPQQNPaFonrTiGJU4pf_rfFFMxg?key=SXlVb0s5dEZqRnMyejh3QkcyR2o3NTFvQzhEaXRB",
  },
  {
    id: "llms-what-how",
    title: "Large Language Models: What Are They And How Do We Use Them?",
    pitch: "Demystifying LLMs for developers building the next wave of AI apps",
    start_at: "2023-10-23T18:00:00",
    tags: ["Tech Talk", "AI", "LLM"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/296408305/",
    cover_url: "/images/meetup/highres_516203971.jpeg",
    host: sponsors.cohere,
    youtubeUrl: "https://www.youtube.com/watch?v=L61l0VzQ5j4",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipPFf6pYTwSxFt1sG8sco1i_tdRYmRzxFSlGLXokJjlMXsc4ZT9288pNP0Z7-_Q71A?key=aVM3VjA3WU5QOW5XaExMLW1BTFoxbkdCQllERDhB",
  },
  {
    id: "junior-to-midlevel",
    title: "From Junior to Mid-Level & Beyond: Strategies for Career Advancement",
    pitch: "Real talk from engineers who made the leap — and what actually helped",
    start_at: "2023-10-18T20:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Beginner-friendly"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/296505054/",
    cover_url: "/images/meetup/highres_516306438.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=xWsj6REFwHA",
  },
  {
    id: "website-performance-deep-dive",
    title: "Loading... A deep dive into website and web app performance",
    pitch: "Tools, techniques, and mental models for faster web experiences",
    start_at: "2023-09-28T18:00:00",
    venue: "Points.com",
    tags: ["Tech Talk", "Performance", "Web Dev"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/295642016/",
    cover_url: "/images/meetup/highres_515354669.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=IKrZuYJGBKo",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipOG-h347VHP9BpUaj9VGXpH1RbYpvM9VqJPbGMPw22afLsIUrmW1Mc9vPDpBBO8tg?key=NVdxWnV2ckFSZG0zeDdyMlVaUS1VNDFCWV9QRTZB",
  },
  {
    id: "bowling-2023",
    title: "Bowling with Techtank",
    pitch: "Where it all began",
    start_at: "2023-09-30T17:00:00",
    venue: "The Ballroom Bowl",
    tags: ["Social"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://lu.ma/om45mvv3",
    cover_url: "/images/luma/default-retro4.jpeg",
    albumUrl:
      "https://photos.google.com/u/2/share/AF1QipNJf7YltaKvL5Cq_bX4O8Nt0heaFeetF1UuqVj54JoxVEzjPm4F85nQPHj_LDKpdw?key=V2JKcjBkTDczWVZWWHNpNUl4OVJGOGQxNmQxb3BB",
  },
  {
    id: "continuous-learning-tech",
    title: "Embracing Continuous Learning: Navigating Skill Development in Tech",
    pitch: "How to keep growing in a fast-moving industry without burning out",
    start_at: "2023-09-06T20:00:00",
    venue: "Online",
    tags: ["Tech Talk", "Career", "Learning"],
    status: "past",
    guest_count: 0,
    eventUrl: "https://www.meetup.com/techtank-to/events/295750233/",
    cover_url: "/images/meetup/highres_515481840.jpeg",
    youtubeUrl: "https://www.youtube.com/watch?v=6Mf6CDJnE4U",
  },
];
