import type { InstagramPost } from "../../constants/instagram-posts";

// Sort by key so the generated file has a stable order and scrape runs produce
// minimal, reviewable diffs.
export function sortByKey(posts: Record<string, InstagramPost>): Record<string, InstagramPost> {
  return Object.fromEntries(
    Object.keys(posts)
      .sort()
      .map((key) => [key, posts[key]]),
  );
}

// JSON.stringify output is also a valid TypeScript object literal, so no AST
// library is needed. Captions (newlines, quotes, emoji) are JSON-escaped.
export function renderGeneratedFile(posts: Record<string, InstagramPost>): string {
  const literal = JSON.stringify(sortByKey(posts), null, 2);
  return `import type { InstagramPost } from "./instagram-posts";

// AUTO-GENERATED by \`pnpm scrape:instagram\`. Do not edit by hand.
// Human curation (the featured set) lives in instagram-featured.ts.
// \`satisfies\` (not a \`: Record\` annotation) preserves the literal key union so
// instagram-featured.ts can type its featured keys against the real post keys.
export const generatedPosts = ${literal} satisfies Record<string, InstagramPost>;
`;
}
